### ISSUE TITLE
Error: attempt to index global 'g' (a nil value)

### ISSUE THREAD

**Issue by abosnjakovic** [lmburns/lf.nvim#1]
Hello, nice plugin.

When I start nvim with this installed using defaults I get 

Error detected while processing /Users/adam/.local/share/nvim/site/pack/packer/start/lf.nvim/plugin/lf.lua:
E5113: Error while calling lua chunk: .../share/nvim/site/pack/packer/start/lf.nvim/plugin/lf.lua:18: attempt to index global 'g' (a nil value)
stack traceback:
        .../share/nvim/site/pack/packer/start/lf.nvim/plugin/lf.lua:18: in main chunk

**Comment by lmburns** [comment]
I tested this now in complete isolation and everything should be just fine. If there is still a problem, please reopen this or create a new issue.
