### ISSUE TITLE
How to make lf window look exactly like my terminal window outside vim?

### ISSUE THREAD

**Issue by GreenSleeper** [lmburns/lf.nvim#15]
I don't want the lf window to take any highlights in my Vim, want it to look like lf in my terminal outside Vim.
How I can do that?

**Comment by lmburns** [comment]
I don't think this program should work in Vim.
However, in my `vim` (not `nvim`) configuration I have the following:

```vim
    set t_Co=256
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    let &t_8u = "\<Esc>[58;2;%lu;%lu;%lum"
	" You should play around with these options turning some off
    " Perhaps the line below is not needed
    set termguicolors
```

For `nvim`, the same applies:

```lua
	vim.o.background = "dark"
	vim.o.termguicolors = true
```

This problem is with your setup. Not this plugin specifically. If those didn't help, google 'how to get truecolor in neovim terminal'.
