### ISSUE TITLE
Unexpected reset of arglist when opening file from LF

### ISSUE THREAD

**Issue by mroavi** [lmburns/lf.nvim#16]
## Issue Description:

Upon opening a file from LF, the arglist unexpectedly resets to only contain the opened file's name, disregarding any previous entries. 

## Steps to Reproduce:

1. Create two test files, `one.md` and `two.md`, using the command:

```
touch one.md two.md
```

2. Open `one.md` with Neovim:

```
nvim one.md
```

3. Within Neovim, run the command `:arg` which outputs `[one.md]`.

4. Open LF using the `:Lf` command. 

5. With LF open, highlight `two.md` and press `enter` to open it.

6. Now run `:arg` command again. This outputs `[/home/mroavi/lf-bug/two.md]`, meaning the arglist has been reset to contain only `two.md`.

## Problem:

This behavior of resetting the arglist to contain only the newly opened file from LF becomes problematic for users who rely on the arglist for various purposes. Ideally, the arglist should retain its previous entries and add any new file opened from LF, rather than completely resetting.

**Comment by mroavi** [comment]
This bug was introduced in ffcacf5dbbda7f523b5450c9c221e04070ab0e6a

**Comment by lmburns** [comment]
All you have to do is change your default command from `drop` to `argedit`.

**Comment by lmburns** [comment]
I added a keybinding for it in the latest commit. It is `<C-g>`
