### ISSUE TITLE
Error: executing Lua callback: /lf.nvim/lua/lf.lua:46: attempt to index field 'Lf' (a nil value)

### ISSUE THREAD

**Issue by luckyvladimir** [lmburns/lf.nvim#17]
Every now and then I get this error running `:Lf` command. Seems like some race condition at Neovim start:

```
Error executing Lua callback: ...cal/share/nvim/site/pack/packer/start/lf.nvim/lua/lf.lua:46: attempt to index field 'Lf' (a nil value)
stack traceback:
        ...cal/share/nvim/site/pack/packer/start/lf.nvim/lua/lf.lua:46: in function 'start'
        ...wall/.local/share/nvim/lazy/lf.nvim/plugin/lf.lua:16: in function <...wall/.local/share/nvim/lazy/lf.nvim/plugin/lf.lua:14>
```

Neovim version: 0.9.0
Package Manager: Lazy

**Comment by lmburns** [comment]
How are you you calling the command? Just simply with `:Lf`?

**Comment by luckyvladimir** [comment]
yeah, simply `:Lf`. The issue doesn't occur consistently, but it appears to be connected to the initialization process. When it does work, it works well. However, about one out of every five times, I start Neovim, the `:Lf` command produces this error.

**Comment by lmburns** [comment]
@luckyvladimir Try to not lazy load the lf.nvim plug-in. I don't use the lazy package manager, I still use packer; however, whenever I first developed this plugin I had to remove lazy-loading of it entirely. It had something to do with its dependency on toggleterm.nvim. 

Let me know if that changes anything

**Comment by luckyvladimir** [comment]
turned out the issue was `toggleterm.nvim` dependency that needs to have the explicit `lazy=false` flag set. with this, I don't have that error anymore. Closing the issue.
