### ISSUE TITLE
Error: attempt to index upvalue 'fs' (a nil value)

### ISSUE THREAD

**Issue by pockethook** [lmburns/lf.nvim#2]
The plugin seems to work fine, but I get the following error when I run `:Lf`:

``Error executing vim.schedule lua callback: ...hare/nvim/site/pack/packer/start/lf.nvim/lua/lf/main.lua:265: attempt to index upvalue 'fs' (a nil value)
stack traceback:
        ...hare/nvim/site/pack/packer/start/lf.nvim/lua/lf/main.lua:265: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
``

**Comment by lmburns** [comment]
I used the newer `fs` module that has been added to neovim nightly but I didn't check whether or not the user had it. 

I will be home before too long and will fix this. Sorry for the inconvenience
