### ISSUE TITLE
Feat: Add the ability to specify custom lf command

### ISSUE THREAD

**Issue by mhdna** [lmburns/lf.nvim#22]
Hi,

Thanks for this super handy plugin!

It would be really useful to have a variable to specify a custom `lf` command so I can add whatever flag I want and do wonders with it. For example, I could add the `-config` flag to specify a minimal `lfrc` for `lf.nvim`, instead of using my original bloated config which includes so many things that I don't need for this plugin, or I can set it to use my `lfrun` script that integrates image previews and stuff like that.

**Comment by lmburns** [comment]
You should be able to set the configuration variable `default_cmd`

**Comment by mhdna** [comment]
Amazing! There was no mention of this variable in the Readme. Thank you so much!
